local_costmap:
    #footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
    robot_radius: 0.3
    footprint_padding: 0.02
    transform_tolerance: 0.2
    update_frequency: 1.5
    publish_frequency: 1.0

    global_frame: map
    robot_base_frame: base_footprint
    #static_map: false
    rolling_window: true

    width: 2.0
    height: 2.0
    resolution: 0.03 #0.015

    plugins:            
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    obstacle_layer:
        observation_sources: laser_scan_sensor
        laser: {data_type: LaserScan, sensor_frame: base_link, topic: /scan_multi, marking: true, clearing: true, min_obstacle_height: -0.05, obstacle_range: 2.0, raytrace_range: 5.0, inf_is_valid: true}
        

    inflation:
        inflation_radius: 0.1
        cost_scaling_factor: 4 # larger number = lower cost elevation
