obstacle_range: 6.0 #1.5
raytrace_range: 8.5 #2.0
#footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
robot_radius: 0.25
map_topic: map
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_footprint
transform_tolerance: 0.2
always_send_full_costmap: true
plugins: 
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
inflation:
    inflation_radius: 1.75    
    cost_scaling_factor: 2.58
cost_factor: 0.55
neutral_cost: 66
lethal_cost: 253