wheel_1L:                                          #               #   
  ID: 1                                    # L-->  # ############# #  <--R
  Return_Delay_Time: 0                             #   #########   #
  Operating_Mode: 1                                      #####
  Profile_Acceleration: 0                                 ###
  Profile_Velocity: 0                                    #####  <--B
wheel_2R:                                                
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0
wheel_3B:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0
